### PR TITLE
fix physdev for bridge

### PR DESCRIPTION
**Pull request by senorsmile**
This fixes the physdev list for a bridge by properly inserting commas

### CODE REVIEW

**Comment by senorsmile** [comment]
this is incorrect.  PR'd too soon.  closing.

**Comment by senorsmile** [comment]
reverified, this is in fact needed to make bridge physdev list work.

**Comment by k0ste** [comment]
Can you also add README.md example for this feature?

**Comment by senorsmile** [comment]
@k0ste done.  This example is taken directly from my working inventory, but it is generic enough to be a good example too.

**Comment by k0ste** [comment]
@senorsmile please rebase all changes to one commit.
Thanks!

**Pull request merged**
